# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Feishu PR Notify'
description: 'A Feishu pr notify of GitHub actions.'
author: 'naiba'

branding:
  # https://actions-cool.github.io/github-action-branding/
  icon: 'file'
  color: 'blue'

inputs:
  GITHUB_TOKEN:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true
    
  feishu_bot_token:
    description: 'feishu custom bot token'
    required: true

  repo_url:
    required: false
    description: 'github pull request url'

  content:
    required: false
    description: 'message content'


runs:
  using: 'node12'
  main: 'dist/index.js'

